### ISSUE TITLE
Implement TODO items in test suite

### ISSUE THREAD

**Issue by clach04** [clach04/jenc-py#6]
* [x] TODO test decryption failure on bad version. e.g. 0000 - https://github.com/clach04/jenc-py/commit/da2070eed57c59b790735db8aaf592d02d1276f0
* [x] TODO test decryption failure on bad password https://github.com/clach04/jenc-py/commit/2fd8aa2167160816d592aee12cef47826d1c8920
* [x] TODO test decryption failure on corrupted file (change a byte, hmac and also payload). Also see https://github.com/clach04/jenc-py/issues/10
